import { InvestmentOption } from './types';

export const INVESTMENT_OPTIONS: InvestmentOption[] = [
  {
    id: 'cta',
    title: 'Cuenta de ahorros digital',
    description: 'Nequi, Nubank, Bancolombia',
    risk: 'Bajo',
    yield: '~6–9% EA',
    minimum: '$0',
    liquidity: 'Inmediata',
    recommended: true,
    color: 'blue',
    icon: 'Wallet',
    details: [
      { label: 'Respaldada por', value: 'Fogafín hasta $50M' },
      { label: 'Mejor para', value: 'Fondo de emergencia' },
      { label: 'Cómo abrir', value: 'Desde el celular, 10 min' },
      { label: 'Comisión', value: 'No (Nequi, Nubank)' },
    ],
  },
  {
    id: 'cdt',
    title: 'CDT (Certificado de Depósito a Término)',
    description: 'Bancolombia, Davivienda, cooperativas',
    risk: 'Bajo',
    yield: '~10–13% EA',
    minimum: '$100.000',
    liquidity: 'Al vencimiento',
    color: 'green',
    icon: 'FileText',
    details: [
      { label: 'Respaldado por', value: 'Fogafín hasta $50M' },
      { label: 'Plazo mínimo', value: '30 días' },
      { label: 'Mejor para', value: 'Ahorro que no necesitas pronto' },
      { label: 'Penaliza retiro', value: 'Sí, antes del plazo' },
    ],
  },
  {
    id: 'fiducia',
    title: 'Fiducia de inversión colectiva',
    description: 'Skandia, Porvenir, Fondo Voluntario de Pensión',
    risk: 'Moderado',
    yield: '~10–16% EA (variable)',
    minimum: '$50.000',
    liquidity: '3–10 días hábiles',
    color: 'purple',
    icon: 'TrendingUp',
    details: [
      { label: 'Vigilada por', value: 'Superfinanciera de Colombia' },
      { label: 'Mejor para', value: 'Ahorro a 2+ años' },
      { label: 'Beneficio extra', value: 'Deducción de renta (FVP)' },
      { label: 'Riesgo', value: 'Puede bajar temporalmente' },
    ],
  },
  {
    id: 'coop',
    title: 'Cooperativa de ahorro vigilada',
    description: 'Confacoop, Cotrafa, sector salud',
    risk: 'Bajo',
    yield: '~8–11% EA',
    minimum: '$20.000',
    liquidity: 'Según reglamento',
    color: 'emerald',
    icon: 'Users',
    details: [
      { label: 'Vigilada por', value: 'Supersolidaria' },
      { label: 'Ventaja', value: 'Créditos fáciles para socios' },
      { label: 'Acceso', value: 'Sector salud tiene convenios' },
      { label: 'Verificar', value: 'Inscrita en Supersolidaria' },
    ],
  },
];
